export const HeroArr = [
  'Abomination',
  'Ancient One',
  'Balder the Brave',
  'Black Cat',
  'The Cabal',
  'Captain America',
  // 'Daken',
  'Deadpool',
  'Ebony Maw',
  'Enchantress',
  'Falcon',
  'Fantastic Four',
  'Gaea',
  'Galactus',
  'Hammer',
  'The Hulk',
  'Iceman',
  'Ironman',
  'J2',
  'Juggernaut',
  'Kaluu',
  'Knull',
  'Lady Deathstrike',
  'Loki',
  'M',
  'Magneto',
  'Namor',
  'Nightcrawler',
  'Occulus',
  'Onslaught',
  'Karen Page',
  'Professor X',
  'Quasar',
  'Quicksilver',
  'Radioactive Man',
  'Red Skull',
  'Sabertooth',
  'Spiderman',
  'Sydney Taine',
  'Thor',
  'Uatu The Watcher',
  'Ultron',
  'Valkyrie',
  'Venom',
  'Walrus',
  'Wolverine',
  'X-Cell',
  'X-23',
  'Yancy Street Gang',
  'Yondu',
  'Zaran',
  'Zabu',
]