import { HeroArr } from '../lib/hero_arr'

// HeroArr.map((hero) => {

// })

export const allHeroInfo = {
  Abomination: {
    name: 'Abomination',
    firstAppearance: 'Tales to Astonish #90 (1967)',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi lacinia quam accumsan ultricies efficitur. Nulla interdum finibus dapibus. Maecenas velit sapien, rhoncus sit amet mollis quis, maximus et purus. Cras sit amet nulla eget nibh facilisis egestas non sed libero. Sed quis diam erat. Proin condimentum sit amet purus aliquet sollicitudin. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed eget faucibus nulla. Quisque velit mauris, consectetur sit amet erat nec, laoreet faucibus justo. Duis sagittis elit quis sem euismod lacinia. Nulla ullamcorper massa est, sit amet viverra ligula faucibus vitae. Aliquam enim ex, porttitor ut ligula at, hendrerit finibus orci. Suspendisse blandit convallis fringilla.Fusce tempus, lectus ac hendrerit commodo, odio orci lacinia ipsum, et porttitor urna ex eget urna. Aliquam vitae arcu leo. Sed eleifend non ante ultricies finibus. Proin sollicitudin nunc et tincidunt efficitur. Morbi sit amet lorem a augue tristique semper. Aliquam et tortor vitae erat egestas consequat commodo eu metus. Nullam sagittis nisi id ex consectetur, ac ullamcorper sem elementum. Etiam non nulla id felis placerat condimentum. Maecenas id gravida nunc. Etiam dignissim sapien quis condimentum vehicula. Nulla vel fermentum mi. Donec rhoncus placerat tristique. Proin metus neque, ornare ac aliquam vel, finibus a nibh. Duis ut velit et dolor ultricies efficitur.',
    imageUrl: 'https://static.wikia.nocookie.net/marveldatabase/images/b/b4/Emil_Blonsky_%28Earth-616%29_from_Hulk_Vol_3_2_cover.jpg/revision/latest/scale-to-width-down/1200?cb=20220905112355'
  },
  Abyss: {
    name: 'Abyss',
    firstAppearance: 'Avengers #1 (2013)',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi lacinia quam accumsan ultricies efficitur. Nulla interdum finibus dapibus. Maecenas velit sapien, rhoncus sit amet mollis quis, maximus et purus. Cras sit amet nulla eget nibh facilisis egestas non sed libero. Sed quis diam erat. Proin condimentum sit amet purus aliquet sollicitudin. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed eget faucibus nulla. Quisque velit mauris, consectetur sit amet erat nec, laoreet faucibus justo. Duis sagittis elit quis sem euismod lacinia. Nulla ullamcorper massa est, sit amet viverra ligula faucibus vitae. Aliquam enim ex, porttitor ut ligula at, hendrerit finibus orci. Suspendisse blandit convallis fringilla.Fusce tempus, lectus ac hendrerit commodo, odio orci lacinia ipsum, et porttitor urna ex eget urna. Aliquam vitae arcu leo. Sed eleifend non ante ultricies finibus. Proin sollicitudin nunc et tincidunt efficitur. Morbi sit amet lorem a augue tristique semper. Aliquam et tortor vitae erat egestas consequat commodo eu metus. Nullam sagittis nisi id ex consectetur, ac ullamcorper sem elementum. Etiam non nulla id felis placerat condimentum. Maecenas id gravida nunc. Etiam dignissim sapien quis condimentum vehicula. Nulla vel fermentum mi. Donec rhoncus placerat tristique. Proin metus neque, ornare ac aliquam vel, finibus a nibh. Duis ut velit et dolor ultricies efficitur.',
    imageUrl: 'https://static.wikia.nocookie.net/marveldatabase/images/6/60/Abyss_%28Ex_Nihilo%29_%28Earth-616%29_from_Avengers_NOW%21_Vol_1_1_001.png/revision/latest?cb=20150202073146'
  },
  Ironman: {
    name: 'Ironman',
    firstAppearance: 'Avengers #1 (2013)',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi lacinia quam accumsan ultricies efficitur. Nulla interdum finibus dapibus. Maecenas velit sapien, rhoncus sit amet mollis quis, maximus et purus. Cras sit amet nulla eget nibh facilisis egestas non sed libero. Sed quis diam erat. Proin condimentum sit amet purus aliquet sollicitudin. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed eget faucibus nulla. Quisque velit mauris, consectetur sit amet erat nec, laoreet faucibus justo. Duis sagittis elit quis sem euismod lacinia. Nulla ullamcorper massa est, sit amet viverra ligula faucibus vitae. Aliquam enim ex, porttitor ut ligula at, hendrerit finibus orci. Suspendisse blandit convallis fringilla.Fusce tempus, lectus ac hendrerit commodo, odio orci lacinia ipsum, et porttitor urna ex eget urna. Aliquam vitae arcu leo. Sed eleifend non ante ultricies finibus. Proin sollicitudin nunc et tincidunt efficitur. Morbi sit amet lorem a augue tristique semper. Aliquam et tortor vitae erat egestas consequat commodo eu metus. Nullam sagittis nisi id ex consectetur, ac ullamcorper sem elementum. Etiam non nulla id felis placerat condimentum. Maecenas id gravida nunc. Etiam dignissim sapien quis condimentum vehicula. Nulla vel fermentum mi. Donec rhoncus placerat tristique. Proin metus neque, ornare ac aliquam vel, finibus a nibh. Duis ut velit et dolor ultricies efficitur.',
    imageUrl: 'https://static.wikia.nocookie.net/marveldatabase/images/6/60/Abyss_%28Ex_Nihilo%29_%28Earth-616%29_from_Avengers_NOW%21_Vol_1_1_001.png/revision/latest?cb=20150202073146'
  },
  Daken: {
    name: 'Daken',
    firstAppearance: 'Avengers #1 (2013)',
    bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi lacinia quam accumsan ultricies efficitur. Nulla interdum finibus dapibus. Maecenas velit sapien, rhoncus sit amet mollis quis, maximus et purus. Cras sit amet nulla eget nibh facilisis egestas non sed libero. Sed quis diam erat. Proin condimentum sit amet purus aliquet sollicitudin. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed eget faucibus nulla. Quisque velit mauris, consectetur sit amet erat nec, laoreet faucibus justo. Duis sagittis elit quis sem euismod lacinia. Nulla ullamcorper massa est, sit amet viverra ligula faucibus vitae. Aliquam enim ex, porttitor ut ligula at, hendrerit finibus orci. Suspendisse blandit convallis fringilla.Fusce tempus, lectus ac hendrerit commodo, odio orci lacinia ipsum, et porttitor urna ex eget urna. Aliquam vitae arcu leo. Sed eleifend non ante ultricies finibus. Proin sollicitudin nunc et tincidunt efficitur. Morbi sit amet lorem a augue tristique semper. Aliquam et tortor vitae erat egestas consequat commodo eu metus. Nullam sagittis nisi id ex consectetur, ac ullamcorper sem elementum. Etiam non nulla id felis placerat condimentum. Maecenas id gravida nunc. Etiam dignissim sapien quis condimentum vehicula. Nulla vel fermentum mi. Donec rhoncus placerat tristique. Proin metus neque, ornare ac aliquam vel, finibus a nibh. Duis ut velit et dolor ultricies efficitur.',
    imageUrl: 'https://static.wikia.nocookie.net/marveldatabase/images/6/60/Abyss_%28Ex_Nihilo%29_%28Earth-616%29_from_Avengers_NOW%21_Vol_1_1_001.png/revision/latest?cb=20150202073146'
  }
}